### ISSUE TITLE
Issue when selecting which artist it should use

### ISSUE THREAD

**Issue by kukosek** [lukelbd/youtube-dl-music#1]
So everytime it asks me and I select a number, it throws an error like this:
```
Retrieving metadata for 'The Dave Brubeck Quartet' - 'Take Five'.
Found 100 recordings...
1: The Dave Brubeck Quartet 
2: Carmen McRae 
3: Boston Pops Esplanade Orchestra 
Which artist number(s) should we use (enter 0 for all)?1
Traceback (most recent call last):
  File "/home/lukas/youtube-dl-music/ydm-metadata", line 1515, in <module>
    recordings = recording_musicbrainz(artist, title)
  File "/home/lukas/youtube-dl-music/ydm-metadata", line 1429, in recording_musicbrainz
    df.loc[artist] = ids  # add ids to dataframe
  File "/home/lukas/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 671, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/home/lukas/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 875, in _setitem_with_indexer
    return self._setitem_with_indexer_missing(indexer, value)
  File "/home/lukas/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1107, in _setitem_with_indexer_missing
    raise ValueError("cannot set a frame with no defined columns")
ValueError: cannot set a frame with no defined columns
ydm [OPTION...] URL ARTIST - TITLE
ydm [OPTION...] URL ARTIST/TITLE
Error: Metadata script failed.
```
This is the only issue now, otherwise this thing is very helpful! Thank you for this.

**Comment by lukelbd** [comment]
Cool to see someone using this! I think cea67ae should fix this, it removes the pandas dependency (which was overkill) and uses python's builtin csv reader instead. If this doesn't fix it, you should also try removing the file `.choices` from the `youtube-dl-music` folder.
