### ISSUE TITLE
runtime error in ydm-metadata

### ISSUE THREAD

**Issue by fsoc** [lukelbd/youtube-dl-music#4]
Hi,

I am using the source code with HEAD a82fa867eb3429bcdb730d71b41ee4602cf50224
python 3.8.5 and the latest dependencies as of sep 16 2020.

There seems to be an error in the ydm-metadata script:

```
ydm https://www.youtube.com/watch?v=A_MjCqQoLLA The Beatles - Hey Jude
URL: https://www.youtube.com/watch?v=A_MjCqQoLLA
Name: 'The Beatles - Hey Jude'
Downloading.
Bitrate: 129kbps
Normalizing volume and saving to mp3.
WARNING: The sample rate will automatically be set to 192 kHz by the loudnorm filter. Specify -ar/--sample-rate to override it.
Bitrate: 193kbps
Adding metadata.
Retrieving metadata for 'The Beatles' - 'Hey Jude'.
Found 100 recordings...
1: The Beatles
2: Kanye West
Which artist number(s) should we use (enter 0 for all)?1
Consolidated 1018 releases into 146 release groups (687 duplicates removed).
Traceback (most recent call last):
  File "/home/xx/apps/youtube-dl-music/ydm-metadata", line 1736, in <module>
    add_metadata(
  File "/home/xx/apps/youtube-dl-music/ydm-metadata", line 823, in add_metadata
    album = album_musicbrainz(
  File "/home/anon/apps/youtube-dl-music/ydm-metadata", line 1009, in album_musicbrainz
    if album and _word_tuple(ialbum) != _word_tuple(album):
  File "/home/xx/apps/youtube-dl-music/ydm-metadata", line 728, in _word_tuple
    for istring in string.split('/'):
AttributeError: 'dict' object has no attribute 'split'
ydm [OPTION...] URL ARTIST - TITLE
ydm [OPTION...] URL ARTIST / TITLE
Error: Metadata script failed.


```

**Comment by lukelbd** [comment]
I think the latest commit should fix this.
