### ISSUE TITLE
Normalization failure

### ISSUE THREAD

**Issue by JakeTrock** [lukelbd/youtube-dl-music#9]
I'm kind of in a hurry right now, but here's the error I'm getting:
`WARNING: The sample rate will automatically be set to 192 kHz by the loudnorm filter. Specify -ar/--sample-rate to override it.
Traceback (most recent call last):
  File "/home/uname/.local/bin/ffmpeg-normalize", line 8, in <module>
    sys.exit(main())
  File "/home/uname/.local/lib/python2.7/site-packages/ffmpeg_normalize/__main__.py", line 471, in main
    ffmpeg_normalize.run_normalization()
  File "/home/uname/.local/lib/python2.7/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 190, in run_normalization
    raise e
AttributeError: 'module' object has no attribute 'quote'
ydm [OPTION...] URL ARTIST - TITLE
ydm [OPTION...] URL ARTIST / TITLE
Error: Normalization failed.
`

**Comment by JakeTrock** [comment]
people on ubuntu just need to run the install again for some reason:
`pip3 install bs4 discogs_client ffmpeg-normalize musicbrainzngs mutagen pillow unidecode youtube-dl`
